Full project changes
richardoppiyo/budget-app pull request #10
Opened 2022-06-30 16:08 UTC by richardoppiyo

In this capstone project, I have implemented the following:

 Splash screen
  -  A simple page with the name of your app (yes, you need to choose one), and links to the sign up and log in pages.
  
Sign up and log in pages
 - The user should be able to register in the app with full name, email and password (all mandatory).
 - The user can log into the app using email and password.
 - If the user is not logged in, they can't access pages that require the user to be logged in (all the pages described below).
 
Home page (catagories page)
 - When the user logs in, they are presented with the categories page.
 - For each category, the user can see their name, icon and the total amount of all the transactions that belongs to that category.
 - When the user clicks (or taps) on a category item, the application navigates to the transactions page for that category.
 - There is a button "add a new category" at the bottom that brings the user to the page to create a new category.
 
Transactions page
 - For a given category, the list of transactions is presented, ordered by the most recent.
 - At the top of the page the user could see the total amount for the category (sum of all of the amounts of the transactions in that category).
 - There is a button "add a new transaction" at the bottom that brings the user to the page to create a new transaction.
 - When the user clicks on the "Back" button (<), the user navigates to the home page.

"Add a new category" page
 - The user fills out a form to create a new category, indicating their name and icon (both mandatory).
 - The user click (or taps) the "Save" button to create the new category, and is taken to the home page on success.
 - When the user clicks on the "Back" button (<), the user navigates to the home page.

"Add a new transaction" page
 - The user fills out a form to create a new transaction with:
        name (mandatory)
        amount (mandatory)
        categories (mandatory at least one)
 - The user click (or taps) the "Save" button to create the new category, and is taken to the transactions page for that category.
 - When the user clicks on the "Back" button (<), the user navigates to the transactions page for that category.

Testing requirements 
 - Create unit and integration tests for all the most important components of your RoR application.

2022-06-30 17:00 UTC, ahmetbozaci requested changes
# ♻️♻️♻️ STATUS: Changes Required  ♻️♻️♻️
![](https://media.giphy.com/media/3pZipqyo1sqHDfJGtz/giphy.gif)

 @richardoppiyo  ✋🏼 

#### Your project is great. You are almost done. However, there are some issues you should fix. Please fix them then your project will be approved.

___ 

### 💯  Nice to have 💯
- Your git-flow is correct. ✔️
- You set up linter files and no errors. ✔️
- Your pull request is very professional. It has a meaningful title and summary. Keep it up.✔️
- You create a presentation video to a demo of the website and show the code that you are proud of it.✔️
- I can't log in if ı am not signup for the website ✔️
- You create tests.✔️

___


### ♻️ Request changes ♻️

- [ ] _Check the comments under the review._

___

### Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
___

### Cheers and Happy coding! 💻 👏
![almost](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)


___

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification._

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._


___

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_

[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

2022-06-30 17:00 UTC, ahmetbozaci commented on app/assets/stylesheets/application.css
> +
- [ ] Kindly use the design's font-family in the all page to follow design guidelines

![image](https://user-images.githubusercontent.com/38635158/176731827-716a0a38-85d9-4a33-a30f-7d5868b831a8.png)

2022-06-30 17:00 UTC, ahmetbozaci commented on README.md
> +This project is [MIT](./LICENSE) licensed.
- [ ] To make a professional readme file please fix the broken link.
- [ ] Kindly add a creative common license. [Requirement](https://github.com/microverseinc/curriculum-rails/blob/main/capstone/rails_capstone.md#:~:text=The%20Creative%20Commons%20license%20of%20the%20design%20requires%20that%20you%20give%20appropriate%20credit%20to%20the%20author.%20Therefore%2C%20you%20must%20do%20it%20in%20the%20README%20of%20your%20project.).
- [ ] Kindly add a design link in the acknowledgment section. [Requirement](https://github.com/microverseinc/curriculum-rails/blob/main/capstone/rails_capstone.md#:~:text=Original%20design%20idea%20by%20Gregoire%20Vella%20on%20Behance.)
- [ ] Please fill the acknowledgment section with proper texts

![image](https://user-images.githubusercontent.com/38635158/176732482-14141343-813f-443f-8035-c8a65dcc0ff3.png)

2022-06-30 17:00 UTC, ahmetbozaci commented on app/controllers/transactions_controller.rb
> +    # @transactions = Group.find(params[:group_id]).transactions.new
- [ ] Kindly remove the commented code to make code clean.

2022-06-30 17:00 UTC, ahmetbozaci commented on app/controllers/transactions_controller.rb
> +  end
- [ ] I can create transactions but it not showing on the page. Kİndly fix the error.
- [ ] After fixing it make sure the list of transactions should be ordered by the most recent. 
![image](https://user-images.githubusercontent.com/38635158/176733336-10ec6e3c-96a6-4f12-81a8-48e8349bd44b.png)

https://user-images.githubusercontent.com/38635158/176733956-0529c179-aa2f-45fd-a5df-1e84cb7d4faf.mp4


![image](https://user-images.githubusercontent.com/38635158/176734233-0e186915-afcb-4503-aa6f-2b8758af6b40.png)

2022-06-30 17:00 UTC, ahmetbozaci commented on app/views/devise/registrations/new.html.erb
> +</div>
OPTIONAL
- [ ] I cant open the website if not signup. Well done. But it will be good show some error to the user

2022-06-30 17:00 UTC, ahmetbozaci commented on app/views/entities/new.html.erb
> +</div>
OPTIONAL

- [ ] Adding an entity is not a requirement. But it is giving an error. YOu can fix it.

![image](https://user-images.githubusercontent.com/38635158/176735316-075ce74f-2826-4937-8794-0e6a73c0c972.png)

2022-06-30 21:13 UTC, richardoppiyo commented
Thank you so much for pointing out the challenge.
I have sorted them out. I am yet to work on the OPTIONALS, because I want to finish the core requirements of the week first as I am behind schedule.
Thank you once again!

2022-06-30 22:05 UTC, codepantha requested changes
# STATUS: REQUESTED CHANGES ♻️ 

## Hi @richardoppiyo 👋, 

Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media3.giphy.com/media/nKN7E76a27Uek/giphy.gif"/>

### Highlights 🎯 
✔️ Descriptive PR
✔️Good commit history
✔️ Linter checks
✔️ Correct GitFlow

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-30 22:05 UTC, codepantha commented on README.md
> +This project is [MIT](./LICENSE) licensed.
- [ ]  Please fix the broken link to the MIT license like the previous reviewer requested 🙏

2022-06-30 22:05 UTC, codepantha commented on app/controllers/transactions_controller.rb
> +  end
- [ ] The functionality to create transactions does not work. Please fix it as requested by the previous reviewer 🙏

2022-06-30 22:05 UTC, codepantha commented on app/views/groups/show.html.erb
> +
- [ ] There is a problem with your routing in this file where you have a link to "Add a new transaction". You can use route names in this case `new_group_transaction_path(@group)`. That should fix your route 😎.You can see route error below 👇 
![image](https://user-images.githubusercontent.com/46839548/176786326-c1cce986-c8ed-4fe0-9390-ff39ee8f9eea.png)

2022-07-01 16:30 UTC, EricMbouwe approved these changes
Hi @richardoppiyo, 

In my opinion, your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 


Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Hi STUDENT, 

In my opinion, your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 


Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2022-07-01 16:58 UTC, merged